services:
  transcendence_backend:
    build:
      context: ./backend
    image: "transcendence_backend:latest"
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - backend_data:/app/data
      - backend_img:/app/img
      - backend_srcs:/app/srcs

  transcendence_frontend:
    build:
      context: ./frontend
      target: production
    image: "transcendence_frontend:latest"
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - transcendence_backend
  
volumes:
  backend_data:
    driver: local
  backend_srcs:
    driver: local
  backend_img:
    driver: local
